import type { Analysis, AnalysisKpis } from '../../types'
import { formatDriverLabel } from '../../lib/driverLabels'
import { formatCompactMoney, formatNumber, formatPct01 } from './format'

export function DecisionBriefPrint({
  analysis,
  kpis,
  datasetName,
  rawColumns,
}: {
  analysis: Analysis
  kpis: AnalysisKpis
  datasetName?: string
  rawColumns?: string[]
}) {
  const rate = kpis.target_level.predicted_target_rate ?? kpis.target_level.target_rate
  const revenue = kpis.impact_revenue?.revenue_at_risk
  const topDriver = kpis.drivers[0]
  const rel = kpis.reliability
  const h = kpis.concentration.headline

  return (
    <div data-decision-brief className="hidden print:block p-8 text-(--text-1) bg-(--surface-1)">
      <p className="text-xs text-(--text-3) uppercase tracking-wide mb-1">RootLens Decision Brief</p>
      <h1 className="text-2xl font-bold mb-1">
        {datasetName ?? 'Dataset'} — {analysis.target} analysis
      </h1>
      <p className="text-sm text-(--text-2) mb-6">
        Run #{analysis.id} · {analysis.completed_at ? new Date(analysis.completed_at).toLocaleDateString() : 'In progress'}
      </p>

      <div className="grid grid-cols-4 gap-4 mb-8 border-b border-(--border-subtle) pb-6">
        <div>
          <p className="text-xs text-(--text-3)">Target rate</p>
          <p className="text-xl font-bold">{rate != null ? formatPct01(rate) : '—'}</p>
        </div>
        <div>
          <p className="text-xs text-(--text-3)">Revenue at risk</p>
          <p className="text-xl font-bold">{revenue != null ? formatCompactMoney(revenue) : '—'}</p>
        </div>
        <div>
          <p className="text-xs text-(--text-3)">Top driver</p>
          <p className="text-lg font-bold">{topDriver ? formatDriverLabel(topDriver.feature, rawColumns) : '—'}</p>
        </div>
        <div>
          <p className="text-xs text-(--text-3)">Confidence</p>
          <p className="text-lg font-bold capitalize">{rel.tier}</p>
          <p className="text-xs text-(--text-3)">{rel.headline_metric}: {formatNumber(rel.headline_value)}</p>
        </div>
      </div>

      <div className="space-y-4 text-sm leading-relaxed">
        <p>
          Top {(h.top_pct_users * 100).toFixed(0)}% of users hold {formatPct01(h.share_of_risk)} of modeled exposure
          (Gini {kpis.concentration.gini.toFixed(2)}).
        </p>
        {topDriver && (
          <p>
            Primary root cause: {formatDriverLabel(topDriver.feature, rawColumns)} ({formatPct01(topDriver.share, 0)} importance).
          </p>
        )}
        <p className="text-(--text-3) text-xs mt-8">Generated by RootLens · Audit-ready artifact</p>
      </div>
    </div>
  )
}
